-- Generated by tools/build_copy.py from game/copy.txt; retain stable line IDs.
local text=[=[
GOOSE
ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
Waiting for game ticket
BADGE MARKET
HTN 26
FAKE MONEY.
Real friends. Questionable decisions.
UP/DOWN choose    A enter
Solo market
Host nearby market
Join nearby market
 SOL
Epoch 
 / all currency is fictional
A market    B games    START hub
UP     Portfolio
DOWN   Launch a meme
LEFT   Nearby / duel
RIGHT  Profile + save
THE EXCHANGE
DIAMOND HANDS
 coins / hold a full epoch for fees
UP/DOWN coin    A view    B hub
No memes yet. DOWN at hub to launch.
  
 / own 
 RUG
Loading coin...
COIN
SYNC
Loading...
Requesting one compact record
B market
RUGGED
LIVE
Owned 
 / holders 
 / meme 
A buy    B sell    START hub
Quantity: 
   LEFT/RIGHT
Supply 
 / treasury 
DOWN creator controls
Hold across epochs. Earn fees.
UP back to market
LAUNCH A MEME
2 SOL
Edit 5-letter ticker / character 
A launch    B cancel    START hub
LEFT/RIGHT choose character
UP/DOWN change letter
One live coin per creator
Price starts at 0.100 SOL
THE GRIND
PLAY
SKILL PAYS.
Earn up to 6 SOL per market epoch.
UP/DOWN choose    A play    B hub
Reaction Trader / earn SOL
Tilt Vault / practice
Badge Duel / nearby
NEARBY MARKETS
NEARBY PLAYERS
BLE
MEET. TRADE.
Host keeps this app open. Range varies.
UP/DOWN choose    A join    B back
UP/DOWN choose    A duel    B back
Market #
Trader #
Open this market on another badge.
YOUR LORE
REP 
 / 100
Creator reputation / rugs 
A save    LEFT dim LEDs    B hub
Title: TRUST ME BRO
Title: FLIGHT RISK
 / epoch 
LED level 
 / AUX toggles
Lua 
 / 
Heap 
 / tick 
CREATOR OFFICE
RISK
Loading
Normal withdrawals use creator fees only
UP/DOWN choose    A confirm    B back
Withdraw 10%
Withdraw 25%
Withdraw 50%
DO SOMETHING TERRIBLE
EXIT LIQUIDITY
DANGER
YOUR REP: COOKED
This drains the fee treasury. Buys stop.
Hold START 3s to rug    B cancel
Holders keep their tokens and SOL.
Their next community reward? Gone.
The goose is watching you.
RUG ALERT
REKT
 RAN AWAY
CREATOR RAN AWAY
Community treasury has left the chat.
A return    HOME saves + exits
HOLD THIS L.
Sells still redeem the curve reserve.
Badge Market / 
 / fake SOL only
 peak=
 free=
 widgets=
 tick_max=
 drops=
WAIT...
BUY!
SELL!
HOLD!
MARKET CLOSED
GET READY
REACTION TRADER
SOLO
Accuracy first. Speed second.
A BUY    B SELL    UP HOLD
Round 
 / 8
Correct 
A claim reward / return
Early press = wrong answer
TILT VAULT
PRACTICE
VAULT OPEN
FIND THE EXIT
Tilt or use D-pad. No SOL farming.
B back    HOME saves + exits
@ 
$ 
# 
. 
HONK! PRESS A
WAIT FOR HONK
DUEL INVITATION
A PERFECT TIE
YOU OUT-HONKED THEM
YOU GOT HONKED
PEER DISCONNECTED
WAITING FOR PEER
BADGE DUEL
VERSUS
Bragging rights. No radio timing advantage.
A accept / react    B cancel
You: false start
You: 
 ms
Them: false start
Them: 
First correct reaction wins.
Choose a market
Not saved
Confirmed
Market full
Sync required
Not enough SOL
Portfolio full
Not enough tokens
Coin unavailable
Launch cooldown
One live coin each
Symbol taken / invalid
Wait 20 seconds
Game proof rejected
Epoch reward cap
Request rejected
Radio unavailable - solo works
Saved market has no room
Restored
Unsaved
25 SOL. Zero consequences.
Joining...
Pending - START retries
Submitting...
Join or host a market first
Retrying same request
Saved
SAVE FAILED
No reply - START retries
MARKET
OK
Market full
Unknown player
Retry sync
Not enough SOL
Bad amount
No holding slot
Not enough tokens
Coin unavailable
Creator only
Launch cooldown
One live coin each
Bad symbol
Wait for cooldown
Invalid game proof
Reward budget empty
Sequence exhausted
]=]
local offsets="\001\000\007\000\044\000\068\000\081\000\088\000\100\000\138\000\164\000\176\000\195\000\214\000\219\000\226\000\255\000\032\001\049\001\070\001\091\001\113\001\126\001\140\001\176\001\208\001\245\001\248\001\000\002\005\002\021\002\026\002\031\002\042\002\072\002\081\002\088\002\093\002\100\002\112\002\121\002\150\002\161\002\175\002\183\002\196\002\218\002\249\002\011\003\025\003\031\003\065\003\099\003\127\003\149\003\175\003\201\003\211\003\216\003\228\003\007\004\041\004\068\004\090\004\110\004\125\004\140\004\144\004\157\004\197\004\232\004\011\005\020\005\029\005\064\005\074\005\079\005\086\005\113\005\146\005\166\005\185\005\195\005\206\005\221\005\226\005\230\005\236\005\245\005\004\006\009\006\017\006\058\006\096\006\109\006\122\006\135\006\157\006\172\006\179\006\196\006\237\006\014\007\049\007\084\007\111\007\121\007\126\007\136\007\153\007\191\007\222\007\235\007\017\008\033\008\050\008\057\008\064\008\074\008\085\008\093\008\101\008\106\008\112\008\118\008\132\008\142\008\158\008\163\008\193\008\220\008\227\008\232\008\241\008\009\009\036\009\047\009\056\009\067\009\081\009\116\009\145\009\148\009\151\009\154\009\157\009\171\009\185\009\201\009\215\009\235\009\250\009\012\010\029\010\040\010\047\010\091\010\120\010\137\010\143\010\147\010\165\010\172\010\201\010\217\010\227\010\237\010\249\010\007\011\022\011\037\011\055\011\072\011\088\011\107\011\130\011\146\011\166\011\183\011\200\011\231\011\000\012\009\012\017\012\044\012\055\012\079\012\093\012\121\012\143\012\149\012\161\012\186\012\193\012\196\012\208\012\223\012\234\012\249\012\004\013\020\013\038\013\055\013\068\013\084\013\103\013\114\013\132\013\151\013\171\013\190\013"
return function(id)
 local a,b=string.unpack("<I2I2",offsets,id*2-1)
 return text:sub(a,b-2)
end
