#!/usr/bin/env python3
"""Build the compact Lua text bank. Line numbers in game/copy.txt are stable IDs."""
from pathlib import Path
import struct
root=Path(__file__).resolve().parents[1]
text=(root/'game/copy.txt').read_text()
assert text.endswith('\n') and ']=]' not in text
offsets=[1]
for line in text.splitlines(keepends=True):offsets.append(offsets[-1]+len(line.encode()))
assert offsets[-1]<65536
raw=struct.pack('<'+'H'*len(offsets),*offsets)
encoded=''.join('\\%03d'%x for x in raw)
(root/'app/badge_market/copy.lua').write_text(
    '-- Generated by tools/build_copy.py from game/copy.txt; retain stable line IDs.\n'
    'local text=[=[\n'+text+']=]\nlocal offsets="'+encoded+'"\n'
    'return function(id)\n local a,b=string.unpack("<I2I2",offsets,id*2-1)\n'
    ' return text:sub(a,b-2)\nend\n')
