#!/usr/bin/env python3
"""Build sorted fixed-width flash dictionaries from reviewed local content."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
words=sorted(set((root/'game/words.txt').read_text().split()))
assert all(len(w)==5 and w.isascii() and w.isalpha() and w.isupper() for w in words)
# Answers are a stable, broad sample; guesses include every curated word.
answers=words[::2]
if 'GOOSE' not in answers: answers=sorted(answers+['GOOSE'])
def array(name,items):
    data=''.join(items)
    return f'static constexpr char {name}[{len(data)}] = {{\n'+''.join('  '+','.join(repr(c) for c in data[i:i+80])+',\n' for i in range(0,len(data),80))+'};\n'
(root/'firmware/core/words.inc').write_text('// Generated by tools/build_words.py; five bytes per record.\n'+array('wordAnswers',answers)+array('wordGuesses',words))
print(len(answers),'answers;',len(words),'valid guesses; flash bytes',5*(len(answers)+len(words)))
